name: Music Mastering Workflow

on:
  push:
    paths:
      - 'MUSIC/*'
  workflow_dispatch:  # Enables manual trigger

permissions:
  contents: write

jobs:
  master_music:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Cache Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # Step 4: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the mastering script on all new/modified tracks
      - name: Run mastering script
        run: |
          mkdir -p MASTERED
          for track in MUSIC/*; do
            filename=$(basename "$track")
            extension="${filename##*.}"
            output="MASTERED/${filename%.*}.mp3"
            python MASTER.py "$track" "$output"
          done

      # Step 6: Commit new mastered tracks and push them to the repository
      - name: Commit new mastered tracks
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only new or changed files in MASTERED
          git add -N MASTERED/*  # Update index
          for file in $(git diff --name-only --diff-filter=A MASTERED/); do
            git add "$file"
            original=$(basename "$file")
            git commit -m "🎧 Auto-mastered track from original: $original"
          done

          git push || echo "No changes to push"
